apiVersion: v1
kind: Service
metadata:
  name: web-static-service
spec:
  selector:
    app: web-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
