apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-static
  template:
    metadata:
      labels:
        app: web-static
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

